<div>
    <form action="<?php echo $block->getHelloAction(); ?>" id="helloForm" method="post" enctype="multipart/form-data" class="form" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
        <table>
            <tbody>
                <tr>
                    <th><?php echo __('Title') ?></th>
                    <td><input type="text" name="title" id="title" value="" class="input-text" data-validate="{required:true}"/></td>
                </tr>
                <tr>
                    <th><?php echo __('Image') ?></th>
                    <td><input type="file" name="image" id="image" value="" class="input-file" data-validate="{required:true,'required-file':true}"/></td>
                </tr>
                <tr>
                    <th><?php echo __('Content') ?></th>
                    <td><textarea name="content" id="content" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea></td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td><button name="submit" type="submit"><?php echo __('Submit') ?></button></td>
                </tr>
            </tfoot>
        </table>
    </form>
</div>