<?php $collection = $block->getCollection(); ?>
<div>
    <div>
        <?php echo $block->getPagerHtml() ?>
        <span>
            <a href="<?php echo $block->getUrl('hello/index');?>"><?php echo __('back To Form Page.') ?></a>
        </span>
    </div>
    <table class="hello_list">
        <thead>
            <tr>
                <th><?php echo __('Title') ?></th>
                <th><?php echo __('Content') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($collection as $hello):?>
                <tr>
                    <td><?php echo $hello->getTitle(); ?></td>
                    <td><?php echo $hello->getContent(); ?></td>
                    <?php if($imageUrl = $block->getImageUrl($hello->getImage())):?>
                        <td><img src="<?php echo $imageUrl; ?>" width="100" /></td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div>
        <img src="<?php echo $block->getUrl('*/*/barcode'); ?>"/>
    </div>
    <script type="text/javascript">
        require(['jquery','Ktpl_Hello/js/toolBar'],function($,toolBar){
            toolBar.apply();
        });
    </script>
</div>
